# Generated by Django 4.0.3 on 2022-03-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg',
            new_name='message',
        ),
    ]
