# Generated by Django 4.0.3 on 2022-03-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_msg_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='value',
        ),
    ]
